// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Product struct {
	ID      string    `json:"id"`
	Name    string    `json:"name"`
	Price   string    `json:"price"`
	Sellers []*Seller `json:"sellers,omitempty"`
}

type Query struct {
}

type Seller struct {
	ID    string `json:"id"`
	Name  string `json:"name"`
	Price string `json:"price"`
}
